version: '3.8'
services:
  api:
    container_name: api-farmasi-simklinik
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=dev
    ports:
      - '3012:4008'
    depends_on:
      - db
    volumes:
    - .:/app
    networks:
      - simklinik
  api-2:
    container_name: api-farmasi-simklinik-2
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=dev
    ports:
      - '3023:4008'
    depends_on:
      - db
    volumes:
    - .:/app
    networks:
      - simklinik
  db:
    container_name: db-farmasi-simklinik
    image: postgres
    ports:
      - '5445:5432'
    volumes:
      - ./Database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - data:/data/simklinik/farmasi
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - simklinik

volumes: 
 data: {}
#define network
networks:
  simklinik:
    driver: bridge
