version: '3.8'
services:
  api:
    container_name: backend-test
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=dev
    ports:
      - '4005:4005'
    depends_on:
      - db
    volumes:
    - .:/app
    networks:
      - backend-test
  db:
    container_name: backend-test-db
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./Database/test.sql:/docker-entrypoint-initdb.d/schema.sql
      - data:/data/simklinik/farmasi
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - backend-test

volumes: 
 data: {}
#define network
networks:
  simklinik:
    driver: bridge
